#Config
MYSQL_HOST = 'YOUR-HOST'
MYSQL_PORT = YOUR-DATABASE-PORT
MYSQL_USER = 'YOUR-DATABASE-USERNAME'
MYSQL_PASS = 'YOUR-DATABASE-PASSWORD'
MYSQL_DB = 'YOUR-DATABASE-NAME'

# You can ignore settings below
MANAGE_PASS = 'shadowsocks2333'
MANAGE_BIND_IP = '127.0.0.1'
MANAGE_PORT = 23333